# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOjCaft7z60zep_CbOQA-QguH1eagYwW
"""

# app.py

# 1. Imports
import streamlit as st
import pandas as pd
import numpy as np
import io

# Optional (if you export Excel + PDF)
from openpyxl import load_workbook
from reportlab.pdfgen import canvas

# 2. Page config (must be near top)
st.set_page_config(
    page_title="Decisio",
    layout="wide"
)

# 3. Title / description
st.title("Decisio — Upload Excel → Get Decisions")
st.write("Upload your Excel file and get actionable insights.")

# 4. File uploader (THIS is the website input)
uploaded_file = st.file_uploader(
    "Upload Excel file (.xlsx)",
    type=["xlsx"]
)

# 5. Guard clause (important)
if not uploaded_file:
    st.info("Please upload an Excel file to continue.")
    st.stop()

# 6. Read Excel (IN MEMORY)
df = pd.read_excel(uploaded_file)

st.subheader("Preview")
st.dataframe(df.head(10))

# 7. Your brain (simplified now, extend later)
def decisio_brain(df: pd.DataFrame) -> dict:
    df = df.copy()
    df.columns = [c.lower() for c in df.columns]

    if "revenue" not in df.columns:
        return {"error": "Column 'revenue' not found"}

    total_revenue = df["revenue"].sum()

    recommendation = (
        "Consider increasing prices by 5–10%"
        if total_revenue > 100_000
        else "Focus on increasing sales volume"
    )

    return {
        "total_revenue": total_revenue,
        "recommendation": recommendation
    }

# 8. Run analysis
if st.button("Run Decisio"):
    try:
        # Read uploaded Excel as bytes
        uploaded_file.seek(0)
        excel_bytes = uploaded_file.read()

        # Call Colab backend
        COLAB_API_BASE = "https://5002-m-s-2texs91f0zgsx-b.us-central1-1.prod.colab.dev"  # paste full URL here

        resp = requests.post(
            f"{COLAB_API_BASE}/analyze",
            files={
                "file": (
                    uploaded_file.name,
                    excel_bytes,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                )
            },
            data={"prompt": prompt},
            timeout=120
        )

        resp.raise_for_status()
        result = resp.json()

        # ----------------------------
        # Display results from Colab
        # ----------------------------
        st.success("Analysis completed")

        st.subheader("Summary")
        st.write(result.get("summary", "No summary returned"))

        if "actions" in result:
            st.subheader("Actions")
            st.dataframe(result["actions"])

        if "tables" in result:
            for name, table in result["tables"].items():
                st.subheader(name)
                st.dataframe(table)

    except requests.exceptions.RequestException as e:
        st.error("Failed to connect to backend")
        st.code(str(e))

    except Exception as e:
        st.error("Unexpected error")
        st.code(str(e))

        # 10. Download button
        st.download_button(
            "Download enriched Excel",
            data=output,
            file_name="decisio_output.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
